version: "3.9"
services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  server:
    build:
      context: ./
      dockerfile: server.Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - mongodb

  dashboard:
    build:
      context: ./
      dockerfile: app.Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - server

volumes:
  mongodb_data_container:
